#!/usr/bin/php
<?php

if (php_sapi_name() !== "cli") {
  exit;
}

define("TYPES", ["title", "author", "publisher", "isbn"]); 

require_once("./classes/Store.php");

$store = new Store("catalog");
$products = $store->getProducts();


if (isset($argv) && !empty($argv)) {
  $search = implode(" ", array_slice($argv, 1));
  foreach(TYPES as $type) {
    $product = $store->searchProducts($search, $type);

    if ($product) break;
  }

  if ($product) {
    foreach($product as $key => $value) {
      print(ucfirst($key) . ": " . $value . "\n");
    }
  } else {
    print("Product Not Found. Please try again.");
  }
}